/c1/rpp_lockstep_host:
  ros__parameters:
    controller_frequency: 100.0
    controller_plugin: nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController
    RPP:
      desired_linear_vel: 1.0
      lookahead_dist: 0.5
      min_lookahead_dist: 0.5
      max_lookahead_dist: 1.0
      lookahead_time: 1.0
      use_velocity_scaled_lookahead_dist: true
      use_interpolation: true
      use_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 1.093722637313
      regulated_linear_scaling_min_speed: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_rotate_to_heading: false
      allow_reversing: false
      max_robot_pose_search_dist: 2.0
