#!/usr/bin/env bash
set -eo pipefail

source /opt/ros/humble/setup.bash
source /home/ubuntu/zed_ws/install/setup.bash
source /home/ubuntu/third_party/third_party_ws/install/setup.bash
source /home/ubuntu/laksa_ws/install/setup.bash

export ROS_DOMAIN_ID=0
export ROS_LOCALHOST_ONLY=1

exec ros2 launch laksa_dashboard cockpit.launch.py
