import * as THREE from '/vendor/three.module.min.js';

const $=id=>document.getElementById(id), state={mapping:{state:'IDLE'},health:{}};
const toast=message=>{const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)};
const val=(v,digits=1)=>v===null||v===undefined?'—':Number(v).toFixed(digits);
const metric=(name,value)=>`<div class="metric"><span>${name}</span><b>${value}</b></div>`;

const scene=new THREE.Scene();scene.background=new THREE.Color(0x050b13);scene.up.set(0,0,1);
const camera=new THREE.PerspectiveCamera(55,1,.02,100);camera.up.set(0,0,1);camera.position.set(3,-4,3);camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('threeView').appendChild(renderer.domElement);
scene.add(new THREE.GridHelper(10,40,0x244a70,0x14283d).rotateX(Math.PI/2));
scene.add(new THREE.AmbientLight(0xffffff,1.5));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(2,-2,4);scene.add(sun);
const robot=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.57,.36,.30),new THREE.MeshStandardMaterial({color:0x1677e8,metalness:.25,roughness:.45}));body.position.set(.135,0,.15);robot.add(body);const nose=new THREE.Mesh(new THREE.ConeGeometry(.06,.15,4),new THREE.MeshStandardMaterial({color:0x32d7ff}));nose.rotation.y=Math.PI/2;nose.position.set(.48,0,.16);robot.add(nose);scene.add(robot);
let cloud=null,trajectory=null,drag=false,px=0,py=0,yaw=-.9,pitch=.55,distance=5;
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-px)*.008;pitch=Math.max(.08,Math.min(1.45,pitch+(e.clientY-py)*.008));px=e.clientX;py=e.clientY});renderer.domElement.addEventListener('wheel',e=>{distance=Math.max(.8,Math.min(20,distance+e.deltaY*.005));e.preventDefault()},{passive:false});
function animate(){requestAnimationFrame(animate);const cp=Math.cos(pitch);camera.position.set(distance*cp*Math.cos(yaw),distance*cp*Math.sin(yaw),distance*Math.sin(pitch));camera.lookAt(robot.position);const box=$('threeView').getBoundingClientRect();renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();renderer.render(scene,camera)}animate();
function setCloud(msg){if(cloud){scene.remove(cloud);cloud.geometry.dispose();cloud.material.dispose()}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(msg.points,3));g.setAttribute('color',new THREE.Float32BufferAttribute(msg.colors,3));cloud=new THREE.Points(g,new THREE.PointsMaterial({size:.035,vertexColors:true,sizeAttenuation:true}));scene.add(cloud);$('pointCount').textContent=`${msg.points.length/3} preview points`}
function setPose(msg){const p=msg.pose;robot.position.set(p[0],p[1],p[2]);robot.quaternion.set(p[3],p[4],p[5],p[6]);if(trajectory){scene.remove(trajectory);trajectory.geometry.dispose()}const flat=msg.trajectory.flat();const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(flat,3));trajectory=new THREE.Line(g,new THREE.LineBasicMaterial({color:0x39d98a}));scene.add(trajectory)}
function setGrid(msg){const canvas=$('occupancy'),ctx=canvas.getContext('2d'),w=msg.width,h=msg.height;if(!w||!h)return;canvas.width=w;canvas.height=h;const image=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const src=y*w+x,dst=((h-1-y)*w+x)*4,v=msg.data[src],c=v<0?38:v===0?224:18;image.data[dst]=c;image.data[dst+1]=v===0?236:c;image.data[dst+2]=v===0?244:c;image.data[dst+3]=255}ctx.putImageData(image,0,0);$('gridSize').textContent=`${w} × ${h} · ${val(msg.resolution,2)} m/cell`}
function mapping(data){state.mapping=data;const active=['STARTING','MAPPING','FINALIZING'].includes(data.state),button=$('mappingButton');$('mappingState').textContent=data.state;$('sessionLine').textContent=data.session_id?`${data.profile} · ${data.session_id} · ${val(data.elapsed_sec,0)} s${data.error?' · '+data.error:''}`:'Ready for a new manual session.';button.textContent=active?'STOP MAPPING':'START MAPPING';button.classList.toggle('stop',active);button.disabled=data.state==='STARTING'||data.state==='FINALIZING';$('profile').disabled=active;$('recordSvo').disabled=active}
function health(data){state.health=data;$('healthStamp').textContent=new Date(data.stamp*1000).toLocaleTimeString();const h=data.health||{};$('healthGrid').innerHTML=['zed','lidar','bno08x','esp32','vesc','xbox','mapping'].map(name=>{const d=h[name]||{},ok=name==='mapping'?d.state!=='ERROR':!!d.connected;return `<div class="health ${ok?'ok':''}"><b><i class="dot"></i>${name.toUpperCase()}</b><small>${name==='mapping'?(d.state||'IDLE'):(ok?'Connected':'Unavailable')}</small></div>`}).join('');const b=data.battery||{};$('battery').innerHTML=metric('Voltage',b.available?`${val(b.voltage_v,2)} V`:'Unavailable')+metric('Input current',b.available?`${val(b.input_current_a,2)} A`:'—')+metric('Motor current',b.available?`${val(b.motor_current_a,2)} A`:'—')+metric('State of charge','Not modeled');const j=data.jetson||{};$('jetson').innerHTML=metric('CPU',`${val(j.cpu_percent)} %`)+metric('GPU',j.gpu_percent===null?'Unsupported':`${val(j.gpu_percent)} %`)+metric('RAM',`${val(j.ram_percent)} %`)+metric('Disk free',`${val(j.disk_free_gb)} GB`);const r=data.vehicle||{};$('robot').innerHTML=metric('Velocity',`${val(r.linear_velocity_mps,3)} m/s`)+metric('Steering target',`${val(r.steering_target_rad,3)} rad`)+metric('Steering measured',`${val(r.steering_current_rad,3)} rad`)+metric('Control','Xbox / ESP32 only');const n=data.network||{};$('network').innerHTML=metric('Hostname',n.hostname||'—')+metric('Connected',n.connected?'Yes':'No')+metric('Interfaces',(n.interfaces||[]).map(i=>`${i.name}: ${i.ipv4.join(', ')}`).join('<br>')||'—')}
async function action(){const active=['STARTING','MAPPING','FINALIZING'].includes(state.mapping.state),url=active?'/api/mapping/stop':'/api/mapping/start',body=active?{}:{profile:$('profile').value,record_svo:$('recordSvo').checked};try{const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await res.json();toast(data.message);if(!res.ok)throw new Error(data.message)}catch(e){toast(`Action failed: ${e.message}`)}}$('mappingButton').addEventListener('click',action);
function connect(){const proto=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${proto}://${location.host}/ws`);ws.onopen=()=>{$('connection').textContent='LIVE';$('connection').className='pill ok';$('cameraFeed').src=`http://${location.hostname}:8080/stream?topic=/zed/zed_node/rgb/color/rect/image&type=mjpeg&quality=65&width=640`};ws.onclose=()=>{$('connection').textContent='RECONNECTING';$('connection').className='pill warn';setTimeout(connect,1500)};ws.onmessage=e=>{if(e.data==='pong')return;const msg=JSON.parse(e.data);if(msg.type==='snapshot'){mapping(msg.data.mapping);if(msg.data.health?.stamp)health(msg.data.health)}else if(msg.type==='mapping')mapping(msg.data);else if(msg.type==='health')health(msg.data);else if(msg.type==='cloud')setCloud(msg);else if(msg.type==='occupancy')setGrid(msg);else if(msg.type==='pose')setPose(msg)}}connect();fetch('/api/state').then(r=>r.json()).then(d=>{mapping(d.mapping);if(d.health?.stamp)health(d.health)});
