import * as THREE from '/vendor/three.module.min.js';

const $=id=>document.getElementById(id);
const state={mapping:{state:'IDLE'},health:{},viewMode:'rotate',follow:false,cameraVisible:false};
const toast=message=>{const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)};
const val=(v,digits=1)=>v===null||v===undefined?'—':Number(v).toFixed(digits);
const metric=(name,value)=>`<div class="metric"><span>${name}</span><b>${value}</b></div>`;
const PROFILE_HELP={
  indoor_live:'Recommended · GEN_3 + NEURAL_LIGHT · Lower compute load',
  indoor_high_quality:'GEN_3 + NEURAL · Higher compute load',
  outdoor_structured:'Experimental / provisional · Not yet validated',
  outdoor_open_field:'Experimental / provisional · Not yet validated'
};
const MODE_LABEL={IDLE:'IDLE',STARTING:'STARTING',MAPPING:'MANUAL MAPPING',FINALIZING:'FINALIZING',COMPLETE:'COMPLETE',ERROR:'ERROR'};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x050b13);scene.up.set(0,0,1);
const camera=new THREE.PerspectiveCamera(55,1,.02,100);camera.up.set(0,0,1);
const threeView=$('threeView');let renderer=null;
try{renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));threeView.prepend(renderer.domElement)}catch(error){const notice=document.createElement('div');notice.className='webgl-notice';notice.textContent='3D rendering is unavailable in this browser. System telemetry remains active.';threeView.prepend(notice);console.warn('LAKSA 3D view unavailable',error)}
scene.add(new THREE.GridHelper(10,40,0x244a70,0x14283d).rotateX(Math.PI/2));
scene.add(new THREE.AmbientLight(0xffffff,1.5));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(2,-2,4);scene.add(sun);
const robot=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.57,.36,.30),new THREE.MeshStandardMaterial({color:0x1677e8,metalness:.25,roughness:.45}));body.position.set(.135,0,.15);robot.add(body);const nose=new THREE.Mesh(new THREE.ConeGeometry(.06,.15,4),new THREE.MeshStandardMaterial({color:0x32d7ff}));nose.rotation.y=Math.PI/2;nose.position.set(.48,0,.16);robot.add(nose);scene.add(robot);
let cloud=null,trajectory=null,drag=false,px=0,py=0,yaw=-.9,pitch=.55,distance=5;
const viewTarget=new THREE.Vector3(0,0,0),cloudBounds=new THREE.Box3();

function syncViewState(){$('threeView').dataset.mode=state.viewMode;$('threeView').dataset.follow=String(state.follow);$('threeView').dataset.distance=distance.toFixed(4);$('threeView').dataset.yaw=yaw.toFixed(4);$('threeView').dataset.pitch=pitch.toFixed(4);$('threeView').dataset.target=[viewTarget.x,viewTarget.y,viewTarget.z].map(v=>v.toFixed(4)).join(',')}
function setViewMode(mode){state.viewMode=mode;for(const id of ['panMode','rotateMode']){const active=(id==='panMode'&&mode==='pan')||(id==='rotateMode'&&mode==='rotate');$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active))}syncViewState()}
function setFollow(enabled){state.follow=enabled;$('followRobot').classList.toggle('active',enabled);$('followRobot').setAttribute('aria-pressed',String(enabled));if(enabled)viewTarget.copy(robot.position);syncViewState()}
function zoom(factor){distance=Math.max(.35,Math.min(30,distance*factor));syncViewState()}
function fitView(){setFollow(false);yaw=-.9;pitch=.65;if(cloud&&cloud.geometry.attributes.position.count){cloud.geometry.computeBoundingBox();cloudBounds.copy(cloud.geometry.boundingBox);const size=new THREE.Vector3();cloudBounds.getCenter(viewTarget);cloudBounds.getSize(size);distance=Math.max(1,Math.min(30,Math.max(size.x,size.y,size.z)*1.9))}else{viewTarget.set(0,0,0);distance=5}syncViewState()}
const interactionSurface=renderer?renderer.domElement:threeView;
interactionSurface.addEventListener('pointerdown',e=>{if(e.target.closest&&e.target.closest('.map-tools'))return;drag=true;px=e.clientX;py=e.clientY;if(interactionSurface.setPointerCapture)interactionSurface.setPointerCapture(e.pointerId);e.preventDefault()});
interactionSurface.addEventListener('pointerup',e=>{drag=false;if(interactionSurface.hasPointerCapture&&interactionSurface.hasPointerCapture(e.pointerId))interactionSurface.releasePointerCapture(e.pointerId)});
interactionSurface.addEventListener('pointercancel',()=>drag=false);
interactionSurface.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;px=e.clientX;py=e.clientY;if(state.viewMode==='rotate'){setFollow(false);yaw-=dx*.008;pitch=Math.max(.08,Math.min(1.48,pitch+dy*.008))}else{setFollow(false);const scale=Math.max(.0008,distance*.0018),right=new THREE.Vector3(-Math.sin(yaw),Math.cos(yaw),0),forward=new THREE.Vector3(Math.cos(yaw),Math.sin(yaw),0);viewTarget.addScaledVector(right,-dx*scale);viewTarget.addScaledVector(forward,dy*scale)}syncViewState();e.preventDefault()});
interactionSurface.addEventListener('wheel',e=>{zoom(e.deltaY>0?1.12:.89);e.preventDefault()},{passive:false});
$('zoomIn').addEventListener('click',()=>zoom(.8));$('zoomOut').addEventListener('click',()=>zoom(1.25));$('panMode').addEventListener('click',()=>setViewMode('pan'));$('rotateMode').addEventListener('click',()=>setViewMode('rotate'));$('followRobot').addEventListener('click',()=>setFollow(!state.follow));$('fitView').addEventListener('click',fitView);
function animate(){requestAnimationFrame(animate);if(state.follow)viewTarget.copy(robot.position);if(!renderer)return;const cp=Math.cos(pitch);camera.position.set(viewTarget.x+distance*cp*Math.cos(yaw),viewTarget.y+distance*cp*Math.sin(yaw),viewTarget.z+distance*Math.sin(pitch));camera.lookAt(viewTarget);const box=threeView.getBoundingClientRect();if(box.width>0&&box.height>0){renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();renderer.render(scene,camera)}}animate();

function setCloud(msg){if(cloud){scene.remove(cloud);cloud.geometry.dispose();cloud.material.dispose()}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(msg.points,3));g.setAttribute('color',new THREE.Float32BufferAttribute(msg.colors,3));cloud=new THREE.Points(g,new THREE.PointsMaterial({size:.035,vertexColors:true,sizeAttenuation:true}));scene.add(cloud);$('pointCount').textContent=`${msg.points.length/3} preview points`}
function setPose(msg){const p=msg.pose;robot.position.set(p[0],p[1],p[2]);robot.quaternion.set(p[3],p[4],p[5],p[6]);if(trajectory){scene.remove(trajectory);trajectory.geometry.dispose()}const flat=msg.trajectory.flat();const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(flat,3));trajectory=new THREE.Line(g,new THREE.LineBasicMaterial({color:0x39d98a}));scene.add(trajectory);if(state.follow)viewTarget.copy(robot.position)}
function setGrid(msg){const canvas=$('occupancy'),ctx=canvas.getContext('2d'),w=msg.width,h=msg.height;if(!w||!h)return;canvas.width=w;canvas.height=h;const image=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const src=y*w+x,dst=((h-1-y)*w+x)*4,v=msg.data[src],c=v<0?38:v===0?224:18;image.data[dst]=c;image.data[dst+1]=v===0?236:c;image.data[dst+2]=v===0?244:c;image.data[dst+3]=255}ctx.putImageData(image,0,0);$('gridSize').textContent=`${w} × ${h} · ${val(msg.resolution,2)} m/cell`}
function mapping(data){state.mapping=data;const active=['STARTING','MAPPING','FINALIZING'].includes(data.state),button=$('mappingButton');$('mappingState').textContent=MODE_LABEL[data.state]||data.state;$('mappingState').classList.toggle('error',data.state==='ERROR');$('sessionLine').textContent=data.session_id?`${data.profile} · ${data.session_id} · ${val(data.elapsed_sec,0)} s${data.error?' · '+data.error:''}`:'Ready for a new manual session.';button.textContent=active?'STOP MAPPING':'START MAPPING';button.classList.toggle('stop',active);button.disabled=data.state==='STARTING'||data.state==='FINALIZING';$('profile').disabled=active;$('recordSvo').disabled=active;if(state.health.stamp)health(state.health)}
function subsystemState(name,d,mapState){const mappingActive=['MAPPING','FINALIZING'].includes(mapState);if(name==='mapping')return d.state==='ERROR'?['error','ERROR']:['online',MODE_LABEL[d.state]||d.state||'IDLE'];if(name==='lidar')return ['disabled','DISABLED'];if(name==='zed'){if(d.connected)return ['online','ONLINE'];if(mapState==='STARTING')return ['standby','STARTING'];return mappingActive?['error','ERROR']:['standby','STANDBY']}if(name==='vesc'){if(d.connected&&d.fault_code)return ['error',`FAULT ${d.fault_code}`];return d.connected?['online','ONLINE']:['standby','NO TELEMETRY']}if(name==='xbox')return d.connected?['online','ONLINE']:['standby','STANDBY'];return d.connected?['online','ONLINE']:['error','ERROR']}
function health(data){state.health=data;$('healthStamp').textContent=new Date(data.stamp*1000).toLocaleTimeString();const h=data.health||{},mapState=state.mapping.state||'IDLE';$('healthGrid').innerHTML=['zed','lidar','bno08x','esp32','vesc','xbox','mapping'].map(name=>{const d=h[name]||{},s=subsystemState(name,d,mapState);return `<div class="health ${s[0]}"><b><i class="dot"></i>${name.toUpperCase()}</b><small>${s[1]}</small></div>`}).join('');const b=data.battery||{};$('battery').innerHTML=metric('Voltage',b.available?`${val(b.voltage_v,2)} V`:'No telemetry')+metric('Input current',b.available?`${val(b.input_current_a,2)} A`:'—')+metric('Motor current',b.available?`${val(b.motor_current_a,2)} A`:'—')+metric('State of charge','Not modeled');const j=data.jetson||{};$('jetson').innerHTML=metric('CPU',`${val(j.cpu_percent)} %`)+metric('GPU',j.gpu_percent===null?'Unsupported':`${val(j.gpu_percent)} %`)+metric('RAM',`${val(j.ram_percent)} %`)+metric('Disk free',`${val(j.disk_free_gb)} GB`);$('diskHint').textContent=j.disk_free_gb===null||j.disk_free_gb===undefined?'':`${val(j.disk_free_gb)} GB free.`;const r=data.vehicle||{};$('robot').innerHTML=metric('Velocity',`${val(r.linear_velocity_mps,3)} m/s`)+metric('Steering target',`${val(r.steering_target_rad,3)} rad`)+metric('Steering measured',`${val(r.steering_current_rad,3)} rad`)+metric('Control','Xbox / ESP32 only');const n=data.network||{},wifi=n.wifi||{};$('network').innerHTML=metric('Hostname',n.hostname||'—')+metric('Wi-Fi',wifi.connected?'Connected':'Disconnected')+metric('SSID',wifi.ssid||'—')+metric('IP',wifi.ipv4||'—');$('networkDetails').innerHTML=(n.interfaces||[]).map(i=>metric(i.name,i.ipv4.join(', ')||'—')).join('')||'<span class="muted">No additional interfaces</span>'}

async function action(){const active=['STARTING','MAPPING','FINALIZING'].includes(state.mapping.state),url=active?'/api/mapping/stop':'/api/mapping/start',body=active?{}:{profile:$('profile').value,record_svo:$('recordSvo').checked};try{const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await res.json();toast(data.message);if(!res.ok)throw new Error(data.message)}catch(e){toast(`Action failed: ${e.message}`)}}
$('mappingButton').addEventListener('click',action);$('profile').addEventListener('change',e=>$('profileHelp').textContent=PROFILE_HELP[e.target.value]);
const blankImage='data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
function cameraDiagnostic(show){state.cameraVisible=show;$('cameraPanel').hidden=!show;$('cameraToggle').textContent=show?'HIDE ZED CAMERA':'SHOW ZED CAMERA';$('cameraToggle').setAttribute('aria-expanded',String(show));const image=$('cameraFeed');if(show){image.src=`http://${location.hostname}:8080/stream?topic=/zed/zed_node/rgb/color/rect/image&type=mjpeg&quality=65&width=640&qos_profile=sensor_data`}else{image.src=blankImage;image.removeAttribute('src')}}
$('cameraToggle').addEventListener('click',()=>cameraDiagnostic(!state.cameraVisible));cameraDiagnostic(false);
function connect(){const proto=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${proto}://${location.host}/ws`);ws.onopen=()=>{$('connection').textContent='LIVE';$('connection').className='pill online'};ws.onclose=()=>{$('connection').textContent='RECONNECTING';$('connection').className='pill standby';setTimeout(connect,1500)};ws.onmessage=e=>{if(e.data==='pong')return;const msg=JSON.parse(e.data);if(msg.type==='snapshot'){mapping(msg.data.mapping);if(msg.data.health?.stamp)health(msg.data.health)}else if(msg.type==='mapping')mapping(msg.data);else if(msg.type==='health')health(msg.data);else if(msg.type==='cloud')setCloud(msg);else if(msg.type==='occupancy')setGrid(msg);else if(msg.type==='pose')setPose(msg)}}
syncViewState();connect();fetch('/api/state').then(r=>r.json()).then(d=>{mapping(d.mapping);if(d.health?.stamp)health(d.health)});
