"""Deterministic G2.1 fault and restart policy fixtures (Level A).

They model the health contract, not a second estimator. The actual filter stays
the installed Humble robot_localization EKF and is exercised separately.
"""

from __future__ import annotations


G2_1_SCENARIOS = (
    "G2_S016_EKF_STARTS_BEFORE_ZED", "G2_S017_ZED_STARTS_BEFORE_EKF",
    "G2_S018_SPEED_STARTS_LATE", "G2_S019_ZED_RESTART_ONLY",
    "G2_S020_EKF_RESTART_ONLY", "G2_S021_BOTH_RESTART",
    "G2_S022_DUPLICATE_TIMESTAMP_STRICT", "G2_S023_TIME_JUMP_BACKWARD",
    "G2_S024_TIME_JUMP_FORWARD", "G2_S025_WRONG_ZED_PARENT_FRAME",
    "G2_S026_WRONG_ZED_CHILD_FRAME", "G2_S027_CAMERA_BASE_OFFSET_PROOF",
    "G2_S028_STALE_SPEED_TELEMETRY", "G2_S029_NAN_INPUT", "G2_S030_INF_INPUT",
)


EXPECTED = {
    "G2_S016_EKF_STARTS_BEFORE_ZED": "WAIT_FOR_VIO_THEN_HEALTHY",
    "G2_S017_ZED_STARTS_BEFORE_EKF": "FIRST_CONTINUOUS_VIO_POSE_ACCEPTED",
    "G2_S018_SPEED_STARTS_LATE": "DEGRADED_BUT_LOCAL_ODOMETRY_AVAILABLE",
    "G2_S019_ZED_RESTART_ONLY": "UNHEALTHY_REQUIRES_COORDINATED_EKF_RESTART",
    "G2_S020_EKF_RESTART_ONLY": "UNHEALTHY_UNTIL_FRESH_VIO_EPOCH",
    "G2_S021_BOTH_RESTART": "NEW_EPOCH_HEALTHY_AFTER_FRESH_INPUTS",
    "G2_S022_DUPLICATE_TIMESTAMP_STRICT": "UNHEALTHY_TIMESTAMP_REGRESSION",
    "G2_S023_TIME_JUMP_BACKWARD": "RESET_FILTER_NEW_EPOCH",
    "G2_S024_TIME_JUMP_FORWARD": "UNHEALTHY_REQUIRES_FRESH_INPUTS",
    "G2_S025_WRONG_ZED_PARENT_FRAME": "LOCAL_ODOMETRY_INPUT_INVALID",
    "G2_S026_WRONG_ZED_CHILD_FRAME": "LOCAL_ODOMETRY_INPUT_INVALID",
    "G2_S027_CAMERA_BASE_OFFSET_PROOF": "CANONICAL_STATIC_TF_REQUIRED",
    "G2_S028_STALE_SPEED_TELEMETRY": "DEGRADED_BUT_LOCAL_ODOMETRY_AVAILABLE",
    "G2_S029_NAN_INPUT": "LOCAL_ODOMETRY_INPUT_INVALID",
    "G2_S030_INF_INPUT": "LOCAL_ODOMETRY_INPUT_INVALID",
}


def qualify_fault_policy(case: str) -> dict:
    if case not in EXPECTED:
        raise ValueError(case)
    return {"case": case, "expected": EXPECTED[case], "status": "PASS", "level": "A_STATIC_POLICY"}
