/bt_navigator:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    always_reload_bt_xml: false
    bt_loop_duration: 20
    default_nav_through_poses_bt_xml: /home/ubuntu/laksa_ws/install/laksa_bringup/share/laksa_bringup/config/navigate_through_poses_ackermann.xml
    default_nav_to_pose_bt_xml: /home/ubuntu/laksa_ws/install/laksa_bringup/share/laksa_bringup/config/navigate_ackermann.xml
    default_server_timeout: 20
    global_frame: map
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    odom_topic: /laksa/odom
    path_blackboard_id: path
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_wait_action_bt_node
    qos_overrides:
      /tf:
        subscription:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        subscription:
          depth: 100
          history: keep_last
          reliability: reliable
    robot_base_frame: laksa_base_footprint
    transform_tolerance: 0.1
    use_sim_time: false
    wait_for_service_timeout: 1000

