/controller_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    FollowPath:
      AckermannConstraints:
        min_turning_r: 1.09
      ConstraintCritic:
        cost_power: 1
        cost_weight: 4.0
        enabled: true
      CostCritic:
        collision_cost: 1000000.0
        consider_footprint: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        enabled: true
        inflation_layer_name: ''
        near_goal_distance: 0.35
      GoalAngleCritic:
        cost_power: 1
        cost_weight: 3.0
        enabled: true
        threshold_to_consider: 0.35
      GoalCritic:
        cost_power: 1
        cost_weight: 5.0
        enabled: true
        threshold_to_consider: 0.9
      PathAlignCritic:
        cost_power: 1
        cost_weight: 10.0
        enabled: true
        max_path_occupancy_ratio: 0.1
        offset_from_furthest: 10
        threshold_to_consider: 0.35
        trajectory_point_step: 3
        use_path_orientations: true
      PathAngleCritic:
        cost_power: 1
        cost_weight: 2.0
        enabled: true
        forward_preference: false
        max_angle_to_furthest: 1.0
        offset_from_furthest: 4
        threshold_to_consider: 0.35
      PathFollowCritic:
        cost_power: 1
        cost_weight: 6.0
        enabled: true
        offset_from_furthest: 5
        threshold_to_consider: 0.9
      PreferForwardCritic:
        cost_power: 1
        cost_weight: 2.0
        enabled: true
        threshold_to_consider: 0.5
      TrajectoryVisualizer:
        time_step: 3
        trajectory_step: 5
      VelocityDeadbandCritic:
        cost_power: 1
        cost_weight: 35.0
        deadband_velocities:
        - 0.217
        - 0.0
        - 0.0
        enabled: true
      batch_size: 900
      critics:
      - ConstraintCritic
      - CostCritic
      - GoalCritic
      - GoalAngleCritic
      - PathAlignCritic
      - PathFollowCritic
      - PathAngleCritic
      - PreferForwardCritic
      - VelocityDeadbandCritic
      enforce_path_inversion: true
      gamma: 0.015
      inversion_xy_tolerance: 0.12
      inversion_yaw_tolerance: 0.35
      iteration_count: 1
      max_robot_pose_search_dist: 2.5
      model_dt: 0.1
      motion_model: Ackermann
      plugin: nav2_mppi_controller::MPPIController
      prune_distance: 1.5
      regenerate_noises: false
      reset_period: 1.0
      retry_attempt_limit: 2
      temperature: 0.3
      time_steps: 48
      transform_tolerance: 0.2
      visualize: false
      vx_max: 0.3621
      vx_min: 0.0
      vx_std: 0.12
      vy_max: 0.0
      vy_std: 0.0
      wz_max: 0.8
      wz_std: 0.25
    controller_frequency: 10.0
    controller_plugins:
    - FollowPath
    controller_server:
      verbose: false
    failure_tolerance: 0.5
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.45
    goal_checker_plugins:
    - goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    odom_topic: /laksa/odom
    progress_checker:
      movement_time_allowance: 30.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.12
    progress_checker_plugin: progress_checker
    publish_zero_velocity: true
    speed_limit_topic: /speed_limit
    use_sim_time: false

