/ekf_filter_node:
  ros__parameters:
    base_link_frame: laksa_base_footprint
    base_link_frame_output: laksa_base_footprint
    control_timeout: 0.0
    debug: false
    diagnostic_updater:
      period: 1.0
      use_fqn: false
    disabled_at_startup: false
    dynamic_process_noise_covariance: false
    frequency: 30.0
    gravitational_acceleration: 9.80665
    history_length: 0.0
    imu0: /laksa/imu/ekf
    imu0_config:
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    imu0_differential: false
    imu0_linear_acceleration_rejection_threshold: 1.7976931348623157e+308
    imu0_pose_rejection_threshold: 1.7976931348623157e+308
    imu0_queue_size: 20
    imu0_relative: false
    imu0_remove_gravitational_acceleration: false
    imu0_twist_rejection_threshold: 1.7976931348623157e+308
    imu1: null
    initial_estimate_covariance: null
    initial_state: null
    map_frame: map
    odom0: /laksa/rf2o_odom
    odom0_config:
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - true
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    odom0_differential: false
    odom0_pose_rejection_threshold: 1.7976931348623157e+308
    odom0_queue_size: 8
    odom0_relative: false
    odom0_twist_rejection_threshold: 2.0
    odom1: /zed/zed_node/odom
    odom1_config:
    - true
    - true
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    odom1_differential: false
    odom1_pose_rejection_threshold: 3.0
    odom1_queue_size: 8
    odom1_relative: false
    odom1_twist_rejection_threshold: 1.7976931348623157e+308
    odom2: /laksa/vesc_odom
    odom2_config:
    - false
    - false
    - false
    - false
    - false
    - false
    - true
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    - false
    odom2_differential: false
    odom2_pose_rejection_threshold: 1.7976931348623157e+308
    odom2_queue_size: 8
    odom2_relative: false
    odom2_twist_rejection_threshold: 2.0
    odom3: null
    odom_frame: laksa_odom
    permit_corrected_publication: false
    pose0: null
    predict_to_current_time: false
    print_diagnostics: true
    process_noise_covariance:
    - 0.05
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.05
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.06
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.03
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.03
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.06
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.03
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.03
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.04
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.02
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.02
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.04
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.05
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.05
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.06
    publish_acceleration: false
    publish_tf: true
    qos_overrides:
      /laksa/odom:
        publisher:
          depth: 10
          history: keep_last
          reliability: reliable
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    reset_on_time_jump: false
    sensor_timeout: 0.25
    smooth_lagged_data: false
    stamped_control: false
    tf_prefix: null
    transform_time_offset: 0.0
    transform_timeout: 0.15
    twist0: null
    two_d_mode: true
    use_control: false
    use_sim_time: false
    world_frame: laksa_odom

